from typing import override
from .net_model import NetModel
from utils.tools import *
from utils.model import *

class DataModel(NetModel):
    """
    Represents a data model used in the ArchNetAI system.

    Args:
        host (str): The host of the model.
        model (str): The model name.

    Attributes:
        client: The client associated with the host.
        options: The options for the model.

    Methods:
        setOptions: Sets the options for the model.
        getModelResponse: Generates a response from the model based on the given context.
        printResult: Prints the response and the time taken to generate it.
        getResponseResult: Returns the response generated by the model.
        printStream: Prints the response and the time taken to generate it.

    """
    @override
    def __init__(self, host, model):
        super().__init__(host, model)
        self.client = self.host.client
        self.resultMask.addType(ResultType.STRING)
        self.resultMask.addType(ResultType.STREAM)
        print("DataModel initialized")


    @override
    def createModelResponse(self, context):
        """
        Generates a response from the model based on the given context.

        Args:
            context (str): The context for generating the response.

        Returns:
            dict: The generated response.

        """
        self.modelResponse = self.client.generate(
            model=self.model,
            prompt=context,
            images=[],
            stream=False,
            format='json',
            options=self.options,
            keep_alive='1m'
        )
        self.isChat = False
